baseURL = "http://example.org/"
languageCode = "en-us"
theme = "split"

title = "Ada Lovelace"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

copyright = "&copy;2020 Ada Lovelace"

[params]

    author = "Ada Lovelace"
    description = "I am a magical code Queen and an enchantress of bits and bytes. I build machine learning models to understand the human brain and mind by writing Python code."
    twitterHandle = "algurlrhythm"

    [params.visual]
        [params.visual.image]
            enable = true
            file = "images/ada-lovelace.jpg"
            position = "center center"

    [[params.links]]
        [params.links.list1]
            heading = "Connect"

            [[params.links.list1.link]]
                text = "Let's Talk"
                url = "person.vcf"
            
            [[params.links.list1.link]]
                text = "Email Me"
                url = "mailto:poojagadige@gmail.com"
            
    [[params.links]]
        [params.links.list2]
            heading = "Social"

            [[params.links.list2.link]]
                text = "LinkedIn"
                url = "https://www.linkedin.com/in/pgadige"
            
            [[params.links.list2.link]]
                text = "Twitter"
                url = "https://twitter.com/algurlrhythm"
    
    [[params.links]]
        [params.links.list3]
            heading = "Work"

            [[params.links.list3.link]]
                text = "Company"
                url = "https://www.adaslist.co/"

